[window]
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal = { family = "Iosevka", style = "Regular" }
size = 14.0

[[keyboard.bindings]]
key = "Enter"
mods = "Shift"
chars = "\u001b[13;2u"

